### PR TITLE
Fix: Report run error specification

### LINKED ISSUE #429: Unable to correlate report run error to specific report
In old GUI:
image

In news GUI the generic error toaster is used:
image

When running 1 or a few report this is not such a problem but when you have a 100 reports and some of the them fail it will be hard to know which error belongs to which report

### PR DESCRIPTION
**Pull request by ricklue**
Closes #429 
Error message is now shown in the test table instead of a toast, so it is clear which error correlates for the specific report.

### CODE REVIEW

File: src/app/test/test.component.ts [hunk 1]
```diff
@@ -153,7 +154,11 @@ export class TestComponent implements OnInit {
         next: (response: TestResult): void => {
           report.reranReport = this.createReranReport(response);
         },
-        error: () => catchError(this.errorHandler.handleError()),
+        error: () =>
+          catchError((error: HttpErrorResponse): Observable<any> => {
+            report.error = error.message;
+            return of(error);
+          }),
```
Comment (MatthijsSmets) [inline src/app/test/test.component.ts:161]: Just wondering, if the http call returns a 500 error from nginx for example, will it paste the entire 500 error html page in the table?

Comment (ricklue) [reply src/app/test/test.component.ts:161]: In the error-handling service we are already using 'error.message', but I was not able to test it, so I am not 100% sure...

Comment (MatthijsSmets) [reply src/app/test/test.component.ts:161]: We'll leave it like this for now, but eventually that should be refactored as well.
